### ISSUE TITLE
fetch json parse error should throw

### ISSUE THREAD

**Issue by Boshen** [teambition/teambition-sdk#235]
https://github.com/teambition/teambition-sdk/blob/master/src/utils/Fetch.ts#L143

it should throw json parse error

**Comment by Brooooooklyn** [comment]
我们一些 API 的返回值有可能是
```json
""
```
一个空字符串，这里是为了处理这种情况

**Comment by Boshen** [comment]
should you make empty string a special case :thinking:

**Comment by Boshen** [comment]
close for now
