### ISSUE TITLE
[讨论] Http 的 send() 方法的名字是否有歧义

### ISSUE THREAD

**Issue by chuan6** [teambition/teambition-sdk#281]
@bjmin 提到 send 方法容易让用户联想到 XHR 的 send 方法，但不像后者那样直接发起一个异步的请求操作（即：前者生成的 Observable<_ResponseType_> 并没有立即被订阅）。

不知道大家怎么看？感觉有歧义吗？如果有，这个方法叫什么名字好？

/cc @Brooooooklyn @Miloas

我（ @chuan6 ）觉得也许 Http 的 send() 方法可以叫做 response$()。

**Comment by Brooooooklyn** [comment]
我们需要达到的目的是在真正的发送请求前有机会修改 defaultHeaders，所以需要在返回 Observable 之前多增加一个步骤。
`send` 方法是借鉴的 [Aurelia](http://aurelia.io/hub.html#/doc/article/aurelia/fetch-client/latest/http-services/3) 确实有一些语义上的问题，它们返回的是 `Promise`。

我翻了一下同样返回 `Observable` 的 Angular Http 模块，好像并不能满足我们的需求。https://angular.io/api/http/Http

@Saviio 有没有什么好的建议？

**Comment by Saviio** [comment]
学golang咯，叫 prepare 如何？

**Comment by bjmin** [comment]
.ready()

**Comment by chuan6** [comment]
在 rx 函数式编程的语境下，我倾向于在这边用名词（如：response$()）。

理由：用户从这个方法获得的是一个包含后端返回的数据的 Observable，不需要关心调用这个方法时是不是有发生什么副作用，而实际上这个方法内部也并没有在网络上做任何事情。

你们觉得呢？

**Comment by Brooooooklyn** [comment]
$ 去掉看起来会好很多, `getResponse()` 如何？

**Comment by Saviio** [comment]
我觉得叫response也不直观啊，因为并没有获得response，按其延迟的特性，叫defer得了...

**Comment by Miloas** [comment]
投一票 `ready()`

**Comment by Brooooooklyn** [comment]
`ready()` 吧，浓浓的 jQuery 风

**Comment by Saviio** [comment]
那就叫ready吧，@chuan6 要不之后就把名字改成ready好了。 (记得bump sdk的时候记得改web里的代码

**Comment by chuan6** [comment]
这个问题搁置有段时间了，刚才有一些想法：
> 尽量避免对偶尔的复杂需求的满足造成日常使用场景中的困扰。目前强大的返回 Http 对象的模式，支持了在请求过程中添加自定义中间逻辑的操作，令 @Miloas 之前在项目中遇到的无解情况变为有解，这是它的价值所在。但日常场景下，并不需要这样添加中间层的操作。

> 那么在不需要使用这一层“间接”操作的用例中，用户就会对写一个函数调用来嫁接而感到困惑。无论它叫什么名字；是现在的 send，还是我们提议的 ready, defer, prepare, getResponse, response$。

> 也许可以给 SDKFetch 上的 get/put/post/delete 添加一个可选的 options 参数如 { defer: boolean }，当我们需要返回 Http，进行更高级的操作，就传入 { defer: true }；当只是简单地发起网络请求，返回 Observable，那就什么都不用传，跟以前一样，如：
> ```
> sdkFetch
>   .get('cities', { province })
>   .filter(() => province !== IGNORED_COUNTRY )
> ```
> 而不是：
> ```
> sdkFetch
>   .get('cities', { province })
>   .send() // 或 .ready()
>   .filter(() => province !== IGNORED_COUNTRY )
> ```
>

这么做可以吗？如果可以的话，我这周就改出来。

**Comment by Saviio** [comment]
我觉得 { defer: boolean } 可以，但是得把类型重载写对，要保证
```
sdkFetch.get('cities', { defer: boolean }) // => return Http Type
sdkFetch.get('cities') // => return Observable Type
```

**Comment by chuan6** [comment]
@Saviio 好的 👌 谢谢提醒，我做做看。
