### ISSUE TITLE
SDKFetch.ts中的get方法对query的特殊情况处理不当

### ISSUE THREAD

**Issue by nekolab** [teambition/teambition-sdk#287]
如果调用 `fetch.get('bar', {})`，实际发出请求的URL形如`foo.com/bar&_=123456789`，而期望访问的是`foo.com/bar?_=123456789`。

另外，`get`方法在加时间戳时没有注意重复的问题，如果调用 `fetch.get('bar', { _: 987654321 })`，实际发出请求的URL是`foo.com/bar?_=987654321&_=123456789` 这显然也是不对的。

**Comment by Saviio** [comment]
PR is welcome :)

**Comment by Miloas** [comment]
（orz ， 应该准备好后再ref过来的）  ...  

@nekolab 应该好了

**Comment by Saviio** [comment]
@Miloas 我有在考虑之后把.Net这个类单独拆出去，这样之后所有的新开的项目就都可以用这个类来做通讯了，或许会更加的模块化，你觉得如何？

teambition-http-client
连带着把所有的API封装掉？

**Comment by Miloas** [comment]
@Saviio 像`angular`的`http`这样吗

**Comment by Saviio** [comment]
明天有空的话找你讨论一下
